[project]
name = "blendercrew"
version = "0.1.0"
description = "blenderCrew using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.98.0,<1.0.0"
]

[project.scripts]
blendercrew = "blendercrew.main:run"
run_crew = "blendercrew.main:run"
train = "blendercrew.main:train"
replay = "blendercrew.main:replay"
test = "blendercrew.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
