[project]
name = "megacrew"
version = "0.1.0"
description = "megacrew using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.98.0,<1.0.0"
]

[project.scripts]
megacrew = "megacrew.main:run"
run_crew = "megacrew.main:run"
train = "megacrew.main:train"
replay = "megacrew.main:replay"
test = "megacrew.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
