import ollama
import time
import os
import json
import numpy as np
from numpy.linalg import norm
import pypdf
from fastapi import FastAPI, BackgroundTasks, status
import uvicorn
from pydantic import BaseModel,Field


app = FastAPI()
global stat
global embeddings
global paragraphs
stat = ""
embeddings = ""
paragraphs = ""

def read_pdf_file(pdf_file):
    with open(pdf_file, 'rb') as file:
        reader = pypdf.PdfReader(file)
        text = ''
        for i in range(reader.get_num_pages()):
            text += reader.get_page(i).extract_text()
    return text


# open a file and return paragraphs
def parse_file(filename,source):
    #with open(filename, encoding="latin-1") as f:
    f=read_pdf_file(filename)
    paragraphs = []
    buffer = []
    path = filename.replace(source+"/","")
    if os.path.exists("embeddings/"+path+"_parse.json"):
        print("load parsing")
        with open(f"embeddings/{path}_parse.json", "r") as f:
            return json.load(f)

    print("build parsing")
    for line in f.split("\n"):
        line = line.strip()
        if line:
            buffer.append(line)
        elif len(buffer):
            paragraphs.append((" ").join(buffer))
            buffer = []
    if len(buffer):
        paragraphs.append(" ".join(buffer))
    # dump paragraphs to json   
    with open(f"embeddings/{path}_parse.json", "w") as f:
        json.dump(paragraphs, f)
    return paragraphs


def save_embeddings(filename, embeddings):
    # create dir if it doesn't exist
    if not os.path.exists("embeddings"):
        os.makedirs("embeddings")
    # dump embeddings to json
    with open(f"embeddings/{filename}.json", "w") as f:
        json.dump(embeddings, f)


def load_embeddings(filename):
    # check if file exists
    if not os.path.exists(f"embeddings/{filename}.json"):
        return False
    # load embeddings from json
    with open(f"embeddings/{filename}.json", "r") as f:
        return json.load(f)


def get_embeddings(filename, modelname, chunks):
    # check if embeddings are already saved
    if (embeddings := load_embeddings(filename)) is not False:
        print("load embedding")
        return embeddings
    # get embeddings from ollama
    print("build embedding")
    embeddings = [
        ollama.embeddings(model=modelname, prompt=chunk)["embedding"]
        for chunk in chunks
    ]
    # save embeddings
    save_embeddings(filename, embeddings)
    return embeddings


# find cosine similarity of every chunk to a given embedding
def find_most_similar(needle, haystack):
    needle_norm = norm(needle)
    similarity_scores = [
        np.dot(needle, item) / (needle_norm * norm(item)) for item in haystack
    ]
    return sorted(zip(similarity_scores, range(len(haystack))), reverse=True)


@app.get("/get_status")
def status():
    global stat
    c = {'status': stat}
    return c

def start():
    # open file
    global embeddings
    global paragraphs
    source = "ressource_documents"
    filename = "ManetteTools.pdf"
    paragraphs = parse_file(source + "/" + filename, source)
    embeddings = get_embeddings(filename, "nomic-embed-text", paragraphs)
    return

@app.post("/ask/")
def ask(prompt): 
    global stat
    global embeddings
    global paragraphs
    #try:
    stat = "WORKING"

    SYSTEM_PROMPT = """Vous êtes un assistant de lecture utile qui repond dans la langue utilisée pour la question.
                en vous basant sur des extraits de texte fournis dans leur contexte. Répondez uniquement en utilisant le contexte fourni,
                en étant aussi concis que possible. Si vous n'êtes pas sûr, dites simplement que vous ne savez pas.
                Context:
                """

    if prompt == "":
        prompt = "que ce que tu peux me dire des manette tools ?"

    if len(embeddings)==0:
        print("reload documents")
        source = "ressource_documents"
        filename = "ManetteTools.pdf"
        paragraphs = parse_file(source + "/" + filename, source)
        embeddings = get_embeddings(filename, "nomic-embed-text", paragraphs)

    # strongly recommended that all embeddings are generated by the same model (don't mix and match)
    prompt_embedding = ollama.embeddings(model="nomic-embed-text", prompt=prompt)["embedding"]
    # find most similar to each other
    most_similar_chunks = find_most_similar(prompt_embedding, embeddings)[:5]

    response = ollama.chat(
        model="mistral",
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT
                           + "\n".join(paragraphs[item[1]] for item in most_similar_chunks),
            },
            {"role": "user", "content": prompt},

        ],
        options={"temperature": 0.0}
    )
    stat = "FINISHED"
    return response["message"]["content"]
    """except:
        stat = "FAILED"
        return stat"""


@app.post("/crew/")
def crewAsk(prompt):
    global stat
    global embeddings
    global paragraphs
    #try:
    stat = "WORKING"

    SYSTEM_PROMPT = """You are a helpful reading assistant
                based on text excerpts provided in context. Answer only using the context provided,
                being as concise as possible. If you are unsure, just say you don't know
                Context:
                """

    if prompt == "":
        prompt = "who are you ?"

    if len(embeddings)==0:
        print("reload documents")
        source = "ressource_documents"
        filename = "geometry_node_editor_guide.pdf"
        paragraphs = parse_file(source + "/" + filename, source)
        embeddings = get_embeddings(filename, "nomic-embed-text", paragraphs)

    # strongly recommended that all embeddings are generated by the same model (don't mix and match)
    prompt_embedding = ollama.embeddings(model="nomic-embed-text", prompt=prompt)["embedding"]
    # find most similar to each other
    most_similar_chunks = find_most_similar(prompt_embedding, embeddings)[:5]
    paraphs = "\n".join(paragraphs[item[1]] for item in most_similar_chunks)
    """response = ollama.chat(
        model="mistral",
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT
                           + "\n".join(paragraphs[item[1]] for item in most_similar_chunks),
            },
            {"role": "user", "content": prompt},

        ],
        options={"temperature": 0.0}
    )"""
    print(paraphs)
    stat = "FINISHED"
    return paraphs #response["message"]["content"]


@app.post("/talk/")
def talk(prompt):
    global stat
    global embeddings
    global paragraphs

    stat = "WORKING"

    SYSTEM_PROMPT = """Vous êtes un assistant utile qui répond aux questions en francais.              
                Si vous n'êtes pas sûr, dites simplement que vous ne savez pas.               
                """

    if prompt == "":
        prompt = "qui est tu ?"


    response = ollama.chat(
        model="mistral",
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            {"role": "user", "content": prompt},

        ],
        options={"temperature": 0.0}
    )
    stat = "FINISHED"
    return response["message"]["content"]


if __name__ == "__main__":
    start()
    uvicorn.run(app)







