[project]
name = "crewone"
version = "0.1.0"
description = "crewOne using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.98.0,<1.0.0"
]

[project.scripts]
crewone = "crewone.main:run"
run_crew = "crewone.main:run"
train = "crewone.main:train"
replay = "crewone.main:replay"
test = "crewone.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
